#!/bin/bash

#SBATCH --qos pq_rcparent
#SBATCH --account=iacc_rcparent
#SBATCH --partition IB_16C_96G
#-SBATCH --partition investor

# Number of nodes
#SBATCH -N 1

# Number of CPU cores
#-SBATCH -n 4

#Total memory requested
#-SBATCH --mem=16000
#-SBATCH --mem=24000
#-SBATCH --mem=32000
#-SBATCH --mem=48000
#SBATCH --mem=60000

export OMP_NUM_THREADS=$SLURM_CPUS_ON_NODE

. $MODULESHOME/../global/profile.modules
module load anaconda/3.5   
#module load anaconda/2.7.13   
pwd; hostname; date
 
echo "Running program on $SLURM_CPUS_ON_NODE CPU cores"
#mv slurm* .out
#jupyter nbconvert --inplace --execute --ExecutePreprocessor.timeout=30001 citation_reader.ipynb
#jupyter nbconvert --inplace --execute --ExecutePreprocessor.timeout=30001 clean_patent.ipynb
#jupyter nbconvert --inplace --execute --ExecutePreprocessor.timeout=300001 clean_uspatentcitation.ipynb
#jupyter nbconvert --inplace --execute --ExecutePreprocessor.timeout=30001 var_builder.ipynb

#jupyter nbconvert --inplace --execute --ExecutePreprocessor.timeout=30001 cit_received.ipynb
#jupyter nbconvert --inplace --execute --ExecutePreprocessor.timeout=30001 cit_made.ipynb

#jupyter nbconvert --inplace --execute --ExecutePreprocessor.timeout=30001 wipo.ipynb
#jupyter nbconvert --inplace --execute --ExecutePreprocessor.timeout=30001 nber.ipynb
#jupyter nbconvert --inplace --execute --ExecutePreprocessor.timeout=30001 cpc.ipynb
#jupyter nbconvert --inplace --execute --ExecutePreprocessor.timeout=30001 ipcr.ipynb
#jupyter nbconvert --inplace --execute --ExecutePreprocessor.timeout=30001 uspc.ipynb

#jupyter nbconvert --inplace --execute --ExecutePreprocessor.timeout=30001 cit_delay.ipynb
#jupyter nbconvert --inplace --execute --ExecutePreprocessor.timeout=30001 cit_tree.ipynb

#jupyter nbconvert --inplace --execute --ExecutePreprocessor.timeout=30001 originality.ipynb
#jupyter nbconvert --inplace --execute --ExecutePreprocessor.timeout=30001 originality_2.ipynb

#jupyter nbconvert --inplace --execute --ExecutePreprocessor.timeout=30001 generality.ipynb
#jupyter nbconvert --inplace --execute --ExecutePreprocessor.timeout=30001 generality_2.ipynb

#jupyter nbconvert --inplace --execute --ExecutePreprocessor.timeout=30001 sampler.ipynb
#
#jupyter nbconvert --inplace --execute --ExecutePreprocessor.timeout=30001 dataset.ipynb

#jupyter nbconvert --inplace --execute --ExecutePreprocessor.timeout=30001 alpha_centrality.ipynb

#jupyter nbconvert --inplace --execute --ExecutePreprocessor.timeout=30001 determinants_patent_citation.ipynb
#jupyter nbconvert --inplace --execute --ExecutePreprocessor.timeout=30001 self_cit.ipynb
#jupyter nbconvert --inplace --execute --ExecutePreprocessor.timeout=30001 internal_external_cit.ipynb

#jupyter nbconvert --inplace --execute --ExecutePreprocessor.timeout=30001 --Application.log_level='DEBUG' int_ext_cit_v2.ipynb
#jupyter nbconvert --inplace --execute --ExecutePreprocessor.timeout=30001 --Application.log_level='DEBUG' int_ext_cit_graphs.ipynb
#jupyter nbconvert --inplace --execute --ExecutePreprocessor.timeout=30001 --Application.log_level='DEBUG' graph_tool-v2.ipynb
#jupyter nbconvert --inplace --execute --ExecutePreprocessor.timeout=30001 graph_tool-v2.ipynb
#python graph_script.py
#jupyter nbconvert --inplace --execute --ExecutePreprocessor.timeout=30001 centrality_analysis.ipynb

#python3 external_knowledge.py
python3 uspatclean_joinselfcit.py

#jupyter nbconvert --inplace --execute --ExecutePreprocessor.timeout=300001 clean_uspatentcitation_update.ipynb

#jupyter nbconvert --inplace --execute --ExecutePreprocessor.timeout=30001 --Application.log_level=50 only_cit_pat.ipynb
#python3 uscleanpat_exclude_name_field.py 
#jupyter nbconvert --inplace --execute --ExecutePreprocessor.timeout=30001 graph_tool-v3.ipynb
#python graph_tool-v2.py
#jupyter nbconvert --inplace --execute --ExecutePreprocessor.timeout=30001 check_uscleanpat_exclude_selfcit.ipynb

date

